version: "3.8"

# remove this line if you don't need a volume to map your dependencies
# volumes:
#   bundle:

services:
  package:
    image: language-name:version
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_PORT=7700
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      # - bundle:/vendor/bundle
      - ./:/home/package

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
