name: meilisearch
description: MeiliSearch Dart is the MeiliSearch API client for Dart and Flutter developers.
version: 0.1.3
homepage: https://github.com/meilisearch/meilisearch-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.0

dev_dependencies:
  test: ^1.0.0
