name: meilisearch
description: MeiliSearch Dart is the MeiliSearch API client for Dart developers. Which you can also use for your Flutter apps as well.
version: 0.1.1+1
homepage: https://github.com/themisir/meilisearch-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.0

dev_dependencies:
  test: ^1.0.0
