name: meili_tool
description: |
  Productivity tools for meilisearch dart repository,
  most of this is inspired from the flutter packages repository https://github.com/flutter/packages/.
version: 1.0.0
repository: https://github.com/meilisearch/meilisearch-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  args: ^2.4.2
  cli_util: ^0.4.0
  file: ^7.0.0
  path: ^1.8.3
  platform: ^3.1.2
  collection: ^1.15.0
  colorize: ^3.0.0
  meta: ^1.10.0
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.3
  matcher: ^0.12.10
  mockito: '>=5.3.2 <=5.4.0'
