# Testing the code base against the Meilisearch pre-releases
name: Pre-Release Tests

# Will only run for PRs and pushes to bump-meilisearch-v*
on:
  push:
    branches:
      - bump-meilisearch-v*
  pull_request:
    branches:
      - bump-meilisearch-v*

jobs:
  integration-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.0.0"]
    name: integration-tests-against-rc (dart ${{ matrix.version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest Meilisearch RC
        run: echo "MEILISEARCH_VERSION=$(curl https://raw.githubusercontent.com/meilisearch/integration-guides/main/scripts/get-latest-meilisearch-rc.sh | bash)" >> $GITHUB_ENV
      - name: Meilisearch (${{ env.MEILISEARCH_VERSION }}) setup with Docker
        run: docker run -d -p 7700:7700 getmeili/meilisearch:${{ env.MEILISEARCH_VERSION }} meilisearch --master-key=masterKey --no-analytics
      - name: Run integration tests
        run: docker run --net="host" -v $PWD:/package -w /package dart:${{ matrix.version }} /bin/sh -c 'dart pub get && dart run test'
