# Testing the code base against the MeiliSearch pre-releases
name: Pre-Release Tests

# Will only run for PRs and pushes to bump-meilisearch-v*
on:
  push:
    branches:
      - bump-meilisearch-v*
  pull_request:
    branches:
      - bump-meilisearch-v*

jobs:
  integration-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['2.7', '2.8']
    name: integration-tests-against-rc (dart ${{ matrix.version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get the latest MeiliSearch RC
        run: echo "MEILISEARCH_VERSION=$(curl https://raw.githubusercontent.com/meilisearch/integration-guides/main/scripts/get-latest-meilisearch-rc.sh | bash)" >> $GITHUB_ENV
      - name: MeiliSearch (${{ env.MEILISEARCH_VERSION }}) setup with Docker
        run: docker run -d -p 7700:7700 getmeili/meilisearch:${{ env.MEILISEARCH_VERSION }} ./meilisearch --master-key=masterKey --no-analytics=true
      - name: Run integration tests
        run: docker run --net="host" -v $PWD:/package -w /package google/dart:${{ matrix.version }} /bin/sh -c 'pub get && pub run test'

